import type { Product } from "./types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: 'MacBook Pro 14"',
    sku: "MBP14M3PRO",
    description: "Laptop z procesorem M3 Pro, 14-calowy ekran Liquid Retina XDR.",
    manufacturer: "Apple",
    category: "Komputery",
    features: ["Bluetooth", "USB-C", "Premium"],
    priceNet: 8129.27,
    priceGross: 9999.0,
    vatRate: 23,
    currency: "PLN",
    available: true,
    limited: false,
    stockQuantity: null,
    minCartQuantity: 1,
    maxCartQuantity: 3,
  },
  {
    id: "2",
    name: "Galaxy S24 Ultra",
    sku: "SGS24U256",
    description: "Flagowy smartfon z rysikiem S Pen i aparatem 200 Mpx.",
    manufacturer: "Samsung",
    category: "Telefony",
    features: ["Bluetooth", "WiFi", "USB-C"],
    priceNet: 5121.95,
    priceGross: 6299.0,
    vatRate: 23,
    currency: "PLN",
    available: true,
    limited: true,
    stockQuantity: 45,
    minCartQuantity: 1,
    maxCartQuantity: 5,
  },
  {
    id: "3",
    name: "Sony WH-1000XM5",
    sku: "SNWH1000XM5",
    description: "Bezprzewodowe słuchawki nauszne z aktywną redukcją szumów.",
    manufacturer: "Sony",
    category: "RTV",
    features: ["Bluetooth", "Bezprzewodowy"],
    priceNet: 1300.0,
    priceGross: 1599.0,
    vatRate: 23,
    currency: "PLN",
    available: true,
    limited: false,
    stockQuantity: null,
    minCartQuantity: 1,
    maxCartQuantity: 10,
  },
  {
    id: "4",
    name: "Bosch Serie 6 WAU28P40",
    sku: "BSWAU28P40",
    description: "Pralka ładowana od przodu, 9 kg, 1400 obr./min.",
    manufacturer: "Bosch",
    category: "AGD",
    features: ["Ekologiczny"],
    priceNet: 2682.11,
    priceGross: 3299.0,
    vatRate: 23,
    currency: "PLN",
    available: false,
    limited: true,
    stockQuantity: 0,
    minCartQuantity: 1,
    maxCartQuantity: 2,
  },
  {
    id: "5",
    name: "Xiaomi Smart Band 8",
    sku: "XMSB8BLK",
    description: "Opaska fitness z ekranem AMOLED i pomiarem tętna.",
    manufacturer: "Xiaomi",
    category: "Akcesoria",
    features: ["Bluetooth", "Wodoodporny"],
    priceNet: 145.53,
    priceGross: 179.0,
    vatRate: 23,
    currency: "PLN",
    available: true,
    limited: false,
    stockQuantity: null,
    minCartQuantity: 1,
    maxCartQuantity: 10,
  },
];
